import { useMemo, useState, useEffect } from "react";
import PageHeader from "../../components/layout/PageHeader.jsx";
import SearchBar from "../../components/ui/SearchBar.jsx";
import FilterBar from "../../components/ui/FilterBar.jsx";
import AlertCard from "../../components/alerts/AlertCard.jsx";
import LoadingState from "../../components/ui/LoadingState.jsx";
import ErrorState from "../../components/ui/ErrorState.jsx";
import EmptyState from "../../components/ui/EmptyState.jsx";
import { getAlerts, updateAlertStatus } from "../../services/apiService.js";
import styles from "../Intelligence/Intelligence.module.css";

export default function Alerts() {
  const [alerts, setAlerts] = useState(null);
  const [status, setStatus] = useState("loading");
  const [query, setQuery] = useState("");
  const [severity, setSeverity] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");

  useEffect(() => {
    let cancelled = false;
    getAlerts()
      .then((data) => {
        if (!cancelled) {
          setAlerts(data);
          setStatus("success");
        }
      })
      .catch(() => !cancelled && setStatus("error"));
    return () => {
      cancelled = true;
    };
  }, []);

  // Actions update local state immediately, then call the (mock) service.
  // This is where a real implementation swaps in the actual PATCH call.
  async function handleStatusChange(alertId, newStatus) {
    setAlerts((prev) => prev.map((a) => (a.id === alertId ? { ...a, status: newStatus } : a)));
    await updateAlertStatus(alertId, newStatus);
  }

  const filtered = useMemo(() => {
    if (!alerts) return [];
    return alerts
      .filter((a) => severity === "all" || a.severity === severity)
      .filter((a) => statusFilter === "all" || a.status === statusFilter)
      .filter((a) => !query.trim() || a.title.toLowerCase().includes(query.toLowerCase()) || a.source.toLowerCase().includes(query.toLowerCase()))
      .sort((a, b) => new Date(b.time) - new Date(a.time));
  }, [alerts, severity, statusFilter, query]);

  if (status === "loading") return <LoadingState label="Loading alerts…" />;
  if (status === "error") return <ErrorState description="Couldn't reach the alert engine." />;

  return (
    <div>
      <PageHeader title="Alerts" subtitle="Alerts generated by the correlation and analysis engines." />

      <div className={styles.toolbar}>
        <SearchBar value={query} onChange={setQuery} placeholder="Search alerts by title or source" />
        <FilterBar
          filters={[
            {
              key: "severity",
              label: "Severity",
              value: severity,
              onChange: setSeverity,
              options: [
                { value: "all", label: "All severities" },
                { value: "critical", label: "Critical" },
                { value: "high", label: "High" },
                { value: "medium", label: "Medium" },
                { value: "low", label: "Low" },
              ],
            },
            {
              key: "status",
              label: "Status",
              value: statusFilter,
              onChange: setStatusFilter,
              options: [
                { value: "all", label: "All statuses" },
                { value: "unacknowledged", label: "Unacknowledged" },
                { value: "acknowledged", label: "Acknowledged" },
                { value: "resolved", label: "Resolved" },
              ],
            },
          ]}
        />
      </div>

      {filtered.length === 0 ? (
        <EmptyState title="No alerts match" description="Try clearing your search or filters." />
      ) : (
        <div className={styles.grid}>
          {filtered.map((alert) => (
            <AlertCard
              key={alert.id}
              alert={alert}
              onAcknowledge={(id) => handleStatusChange(id, "acknowledged")}
              onResolve={(id) => handleStatusChange(id, "resolved")}
            />
          ))}
        </div>
      )}
    </div>
  );
}
