import { useMemo, useState } from "react";
import { useOutletContext } from "react-router-dom";
import PageHeader from "../../components/layout/PageHeader.jsx";
import SearchBar from "../../components/ui/SearchBar.jsx";
import FilterBar from "../../components/ui/FilterBar.jsx";
import AlertCard from "../../components/alerts/AlertCard.jsx";
import LoadingState from "../../components/ui/LoadingState.jsx";
import ErrorState from "../../components/ui/ErrorState.jsx";
import EmptyState from "../../components/ui/EmptyState.jsx";
import styles from "../Intelligence/Intelligence.module.css";

export default function Alerts() {
  const {
    alerts,
    alertsStatus,
    alertsError,
    reloadAlerts,
    onAlertStatusChange,
  } = useOutletContext();
  const [query, setQuery] = useState("");
  const [severity, setSeverity] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");

  // Actions update local state immediately, then call the (mock) service.
  // This is where a real implementation swaps in the actual PATCH call.
  async function handleStatusChange(alertId, newStatus) {
    await onAlertStatusChange(alertId, newStatus);
  }

  const filtered = useMemo(() => {
    if (!alerts) return [];
    return alerts
      .filter((a) => severity === "all" || a.severity === severity)
      .filter((a) => statusFilter === "all" || a.status === statusFilter)
      .filter(
        (a) =>
          !query.trim() ||
          a.title.toLowerCase().includes(query.toLowerCase()) ||
          a.source.toLowerCase().includes(query.toLowerCase()),
      )
      .sort((a, b) => new Date(b.time) - new Date(a.time));
  }, [alerts, severity, statusFilter, query]);

  if (alertsStatus === "loading")
    return <LoadingState label="Loading alerts…" />;
  if (alertsStatus === "error") {
    return (
      <ErrorState
        onRetry={reloadAlerts}
        description={alertsError?.message ?? "Couldn't reach the alert engine."}
      />
    );
  }

  return (
    <div>
      <PageHeader
        title="Alerts"
        subtitle="Alerts generated by the correlation and analysis engines."
      />

      <div className={styles.toolbar}>
        <SearchBar
          value={query}
          onChange={setQuery}
          placeholder="Search alerts by title or source"
        />
        <FilterBar
          filters={[
            {
              key: "severity",
              label: "Severity",
              value: severity,
              onChange: setSeverity,
              options: [
                { value: "all", label: "All severities" },
                { value: "critical", label: "Critical" },
                { value: "high", label: "High" },
                { value: "medium", label: "Medium" },
                { value: "low", label: "Low" },
              ],
            },
            {
              key: "status",
              label: "Status",
              value: statusFilter,
              onChange: setStatusFilter,
              options: [
                { value: "all", label: "All statuses" },
                { value: "unacknowledged", label: "Unacknowledged" },
                { value: "acknowledged", label: "Acknowledged" },
                { value: "resolved", label: "Resolved" },
              ],
            },
          ]}
        />
      </div>

      {filtered.length === 0 ? (
        <EmptyState
          title="No alerts match"
          description="Try clearing your search or filters."
        />
      ) : (
        <div className={styles.grid}>
          {filtered.map((alert) => (
            <AlertCard
              key={alert.id}
              alert={alert}
              onAcknowledge={(id) => handleStatusChange(id, "acknowledged")}
              onResolve={(id) => handleStatusChange(id, "resolved")}
            />
          ))}
        </div>
      )}
    </div>
  );
}
